---
title: "Robustness Check - Cutting Panic Short"
author: "Lieve Heyrman"
date: "2024-07-10"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r set up file}

rm(list=ls())

library(here)

# set project_path
project_path <- here::here()

# set path to data files (depending on operating computer)
location <- "local"
if (location == "server") {
  if (Sys.info()["nodename"] == "GHUM-L-E939DCHK"){
    data_path <- "X:/Retailing_Group_RawData/Hoarding data"
  }else if (Sys.info()["nodename"] == "GHUM-L-E0376K0Q") {
    data_path <- "X:/Retailing_Group_RawData/Hoarding data" }
} else if (location == "local") { 
  if (Sys.info()["nodename"] == "GHUM-L-E939DCHK"){
    data_path <- ""
  }else if (Sys.info()["nodename"] == "GHUM-L-E0376K0Q") {
    data_path <- "C:/PhD KU Leuven/AiMark" } 
}

# load libraries
list.of.packages <- c("plyr","tidyr","ggplot2", "tidyverse", "zoo", "readxl", "car", "sampleSelection", "stargazer", "haven","expss", "plm", "sandwich", "lmtest")
# Install package if they are not installed yet
new.packages <- list.of.packages[!(list.of.packages %in% installed.packages()[,"Package"])]
if(length(new.packages)) install.packages(new.packages)
# Load packages
lapply(list.of.packages, require, character.only = TRUE)

# Suppress summarise info
options(dplyr.summarise.inform = FALSE)

options(scipen = 999)

# create country list
country_list <- c("NL","BE","GE","FR","UK")
# set country
country <- country_list[country_list=="NL"]

```



# LIMITING THE PANIC PERIOD

As a robustness check, we cut the panic period short on various dates (namely, April 20, April 10, March 31).

```{r limiting the panic period}

load(paste(project_path,"/INC-QUANT model/toilet paper/FullData_with_moderators_and_labels.RData",sep=""))

### TOBIT 2 - HECKMAN SELECTION MODEL ###
# main model
library(modelsummary)
# main effects only, including consumer characteristics as controls (not interacted)


# cutting panic short on April 20
#temp.dates <- seq(from = as.Date("2019-01-01"), to = as.Date("2020-04-20"), by = "days")
# cutting panic short on April 10
#temp.dates <- seq(from = as.Date("2019-01-01"), to = as.Date("2020-04-10"), by = "days")
# cutting panic short on March 31
temp.dates <- seq(from = as.Date("2019-01-01"), to = as.Date("2020-03-31"), by = "days")

FullData <- FullData[FullData$Date %in% temp.dates,]
heckman_main <- selection(selection = !is.na(Total_volume_sales) ~  PromoIndex + PanicIndex 
                                      + HouseholdInventory + PriceIndex
                                      + Average_IPT + PromoSensitivity + PLShare + BrandLoyalty
                                      + Age + HouseholdSize + Income + Day_of_week + Week + Year,
                          outcome =          Total_volume_sales  ~  PromoIndex + PanicIndex 
                                      + HouseholdInventory + PriceIndex
                                      + Average_Q + PromoSensitivity + PLShare + BrandLoyalty
                                      + Age + HouseholdSize + Income + Day_of_week + Week + Year,
                          data = FullData, method ="2step")
modelsummary(heckman_main, shape = term + statistic ~ component, stars = T,
             #coef_map = c("(Intercept)" = "Intercept", "PanicIndex" = "Panic Index", "PromoIndex" = "Promo Index", "PriceIndex" = "Price Index", "HouseholdInventory" = "Household Inventory", "Average_IPT" = "Average IPT", "Average_Q" = "Average Q", "PromoSensitivity" = "Promo Sensitivity", "PLShare" = "PL Share", "BrandLoyalty" = "Brand Loyalty", "Age" = "Age", "HouseholdSize" = "Household Size", "Income" = "Income"),
             statistic = c("std.error", "p.value"))

rm(heckman_main, temp.dates, FullData)

```















